version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: webapp:2.0
    ports:
      - "8000:5000"
    restart: always
    networks:
      - webnet
networks:
  webnet:
